export const SELECT_UNIVERSITY = 'SELECT_UNIVERSITY';
export const SHOW_GRADES_TABLE = 'SHOW_GRADES_TABLE';
export const SUBMIT_GRADES = 'SUBMIT_GRADES';
export const SHOW_KALC_RESULTS = 'SHOW_KALC_RESULTS';
export const SUBMIT_GRADES_FORM = 'SUBMIT_GRADES_FORM';
export const LOAD_PERSISTED_STATE = 'LOAD_PERSISTED_STATE';
